server:
  port: 9003

spring:
  application:
    name: cloud-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
        username: nacos
        password: nacos
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
      circuitbreaker:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

# 服务熔断
resilience4j:
  timelimiter:
    instances:
      default:
        timeoutDuration: 4s
        cancelRunningFuture: true

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # 记录速率100%


