server:
  port: 9001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springCloud
    username: ty
    password: 1234qwer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        # 流控规则
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            username: ${spring.cloud.nacos.discovery.username}
            password: ${spring.cloud.nacos.discovery.password}
            group-id: sentinel-group
            data-id: ${spring.application.name}-sentinel-flow-rules
            data-type: json
            # 规则类型：flow、degrade、param-flow、system、authority
            rule-type: flow
        # 熔断降级
#        degrade:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            username: ${spring.cloud.nacos.discovery.username}
#            password: ${spring.cloud.nacos.discovery.password}
#            group-id: sentinel-group
#            data-id: ${spring.application.name}-sentinel-degrade-rules
#            data-type: json
#            rule-type: degrade
#        # 热点规则
#        param-flow:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            username: ${spring.cloud.nacos.discovery.username}
#            password: ${spring.cloud.nacos.discovery.password}
#            group-id: sentinel-group
#            data-id: ${spring.application.name}-sentinel-param-flow-rules
#            data-type: json
#            rule-type: param-flow
#        # 系统规则
#        system:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            username: ${spring.cloud.nacos.discovery.username}
#            password: ${spring.cloud.nacos.discovery.password}
#            group-id: sentinel-group
#            data-id: ${spring.application.name}-sentinel-system-rules
#            data-type: json
#            rule-type: system
#        # 授权规则
#        authority:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            username: ${spring.cloud.nacos.discovery.username}
#            password: ${spring.cloud.nacos.discovery.password}
#            group-id: sentinel-group
#            data-id: ${spring.application.name}-sentinel-authority-rules
#            data-type: json
#            rule-type: authority
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # 记录速率100%


